import * as fs from 'fs';
import * as path from 'path';
import { ReviewState, ReviewComment } from './orchestrator.js';

// Color logging helpers for terminal
const RESET = '\x1b[0m';
const BOLD = '\x1b[1m';
const RED = '\x1b[31m';
const YELLOW = '\x1b[33m';
const CYAN = '\x1b[36m';
const GREEN = '\x1b[32m';

/**
 * Outputs the review findings to the console with beautiful coloring.
 */
export function reportToConsole(state: ReviewState): void {
  const { comments } = state;
  console.log(`\n${BOLD}==================================================`);
  console.log(`🚀 ${GREEN}GEMINI CODE REVIEW COMPLETE${RESET}`);
  console.log(`${BOLD}==================================================${RESET}`);

  if (comments.length === 0) {
    console.log(`\n✨ ${GREEN}No issues found! Your code looks clean and solid.${RESET}\n`);
    return;
  }

  const highCount = comments.filter(c => c.severity === 'HIGH').length;
  const medCount = comments.filter(c => c.severity === 'MEDIUM').length;
  const lowCount = comments.filter(c => c.severity === 'LOW').length;

  console.log(`\nFound ${BOLD}${comments.length} issues${RESET}:`);
  console.log(`- 🔴 ${RED}${highCount} High severity${RESET}`);
  console.log(`- 🟡 ${YELLOW}${medCount} Medium severity${RESET}`);
  console.log(`- 🔵 ${CYAN}${lowCount} Low severity${RESET}\n`);

  comments.forEach((c, index) => {
    let severityColor = CYAN;
    let severityIcon = '🔵';
    if (c.severity === 'HIGH') {
      severityColor = RED;
      severityIcon = '🔴';
    } else if (c.severity === 'MEDIUM') {
      severityColor = YELLOW;
      severityIcon = '🟡';
    }

    console.log(`${BOLD}${index + 1}. ${severityIcon} ${severityColor}[${c.severity}]${RESET} ${BOLD}${c.category}:${RESET} ${c.title}`);
    console.log(`   ${BOLD}File:${RESET} ${c.filePath}:${c.line}`);
    console.log(`   ${BOLD}Problem:${RESET} ${c.problem}`);
    console.log(`   ${BOLD}Consequences:${RESET} ${c.consequences}`);
    if (c.suggestedPatch) {
      console.log(`   ${BOLD}Suggested Fix Available in REVIEW_REPORT.md${RESET}`);
    }
    console.log('-'.repeat(50));
  });

  console.log(`\n📝 ${BOLD}Detailed report written to: REVIEW_REPORT.md${RESET}\n`);
}

/**
 * Writes an educational Markdown report to `REVIEW_REPORT.md` in the git root.
 */
export function writeMarkdownReport(state: ReviewState): void {
  const reportPath = path.join(state.repoRoot, 'REVIEW_REPORT.md');

  const highCount = state.comments.filter(c => c.severity === 'HIGH').length;
  const medCount = state.comments.filter(c => c.severity === 'MEDIUM').length;
  const lowCount = state.comments.filter(c => c.severity === 'LOW').length;

  let mdContent = `# 🚀 AI Code Review Report\n\n`;
  mdContent += `This report was automatically generated by the Gemini Code Reviewer. It contains deep, educational analysis of your staged/unstaged changes.\n\n`;

  // Summary Card
  mdContent += `## 📊 Review Summary\n\n`;
  if (state.comments.length === 0) {
    mdContent += `> ✨ **No issues found!** Your code looks clean, robust, and well-structured.\n\n`;
  } else {
    mdContent += `* **Total Issues**: ${state.comments.length}\n`;
    mdContent += `* 🔴 **High Severity**: ${highCount}\n`;
    mdContent += `* 🟡 **Medium Severity**: ${medCount}\n`;
    mdContent += `* 🔵 **Low Severity**: ${lowCount}\n\n`;
    if (state.plannerGoals) {
      mdContent += `> **Overall Goals/Focus of this Review**: ${state.plannerGoals}\n\n`;
    }
  }

  // Group by File Path
  const commentsByFile: Record<string, ReviewComment[]> = {};
  state.comments.forEach(c => {
    if (!commentsByFile[c.filePath]) {
      commentsByFile[c.filePath] = [];
    }
    commentsByFile[c.filePath].push(c);
  });

  if (state.comments.length > 0) {
    mdContent += `## 🔍 Findings by File\n\n`;

    Object.entries(commentsByFile).forEach(([filePath, fileComments]) => {
      const fileUrl = `file:///${state.repoRoot.replace(/\\/g, '/')}/${filePath}`;
      mdContent += `### 📁 File: [${path.basename(filePath)}](${fileUrl})\n`;
      mdContent += `Path: \`${filePath}\`\n\n`;

      fileComments.forEach(c => {
        let severityIcon = '🔵';
        if (c.severity === 'HIGH') severityIcon = '🔴';
        if (c.severity === 'MEDIUM') severityIcon = '🟡';

        mdContent += `#### ${severityIcon} **${c.severity}** | **${c.category}**: ${c.title}\n`;
        mdContent += `* **Line**: [${c.line}](${fileUrl}#L${c.line})\n`;
        mdContent += `* **The Problem**: ${c.problem}\n`;
        mdContent += `* **Why It Matters (Concept)**: ${c.whyItMatters}\n`;
        mdContent += `* **Consequences**: *${c.consequences}*\n\n`;

        if (c.suggestedPatch) {
          // Format as a markdown diff block or code block
          mdContent += `**Suggested Solution:**\n`;
          mdContent += `\`\`\`diff\n`;
          
          // Split the patch into lines and prefix if not already formatted as a diff
          const patchLines = c.suggestedPatch.split('\n');
          const formattedPatch = patchLines.map(l => {
            if (l.startsWith('+') || l.startsWith('-')) return l;
            return `+ ${l}`; // default to green line if model forgot prefix
          }).join('\n');

          mdContent += `${formattedPatch}\n`;
          mdContent += `\`\`\`\n\n`;
        }

        mdContent += `---\n\n`;
      });
    });

    // Add educational takeaways section
    mdContent += `## 🎓 Senior Engineer Lessons learned\n\n`;
    mdContent += `Here is a summary of the concepts and design principles raised in this review. Use these to strengthen your codebase and development practices:\n\n`;

    const uniqueTakeaways = Array.from(new Set(state.comments.map(c => `* **${c.category} (${c.title})**: ${c.whyItMatters}`)));
    mdContent += uniqueTakeaways.join('\n\n') + '\n';
  }

  fs.writeFileSync(reportPath, mdContent, 'utf-8');
}

/**
 * Writes an educational, interactive, premium HTML report to `REVIEW_REPORT.html` in the git root.
 */
export function writeHtmlReport(state: ReviewState): void {
  const reportPath = path.join(state.repoRoot, 'REVIEW_REPORT.html');

  const highCount = state.comments.filter(c => c.severity === 'HIGH').length;
  const medCount = state.comments.filter(c => c.severity === 'MEDIUM').length;
  const lowCount = state.comments.filter(c => c.severity === 'LOW').length;
  const totalCount = state.comments.length;

  // Code Health Score Formula
  const score = totalCount === 0 
    ? 100 
    : Math.max(0, 100 - (highCount * 15) - (medCount * 7) - (lowCount * 3));

  let grade = 'A+';
  let gradeColor = '#10b981';
  if (score < 60) { grade = 'F'; gradeColor = '#ef4444'; }
  else if (score < 70) { grade = 'D'; gradeColor = '#f97316'; }
  else if (score < 80) { grade = 'C'; gradeColor = '#fbbf24'; }
  else if (score < 90) { grade = 'B'; gradeColor = '#a855f7'; }
  else if (score < 95) { grade = 'A'; gradeColor = '#10b981'; }

  // Unique list of files
  const filePaths = Array.from(new Set(state.comments.map(c => c.filePath)));
  
  // Group comments by file
  const commentsByFile: Record<string, ReviewComment[]> = {};
  state.comments.forEach(c => {
    if (!commentsByFile[c.filePath]) {
      commentsByFile[c.filePath] = [];
    }
    commentsByFile[c.filePath].push(c);
  });

  const fileListHtml = filePaths.map(filePath => {
    const fileCount = commentsByFile[filePath].length;
    const baseName = path.basename(filePath);
    return `
          <div class="file-item" data-filepath="${filePath}">
            <span class="file-name" title="${filePath}">${baseName}</span>
            <span class="file-badge">${fileCount}</span>
          </div>`;
  }).join('');

  const formatDiffToHtml = (patch: string): string => {
    const lines = patch.split('\n');
    return lines.map(line => {
      let cls = 'diff-context';
      let prefix = ' ';
      let text = line;
      if (line.startsWith('+')) {
        cls = 'diff-add';
        prefix = '+';
        text = line.slice(1);
      } else if (line.startsWith('-')) {
        cls = 'diff-delete';
        prefix = '-';
        text = line.slice(1);
      }
      const escapedText = text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
      return `<div class="diff-line ${cls}"><span class="diff-prefix">${prefix}</span><span class="diff-text">${escapedText}</span></div>`;
    }).join('');
  };

  const escapeHtml = (text: string): string => {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  };

  // Build findings cards
  let findingsHtml = '';
  if (totalCount === 0) {
    findingsHtml = `
      <div class="empty-state" style="display: flex;">
        <span class="empty-state-icon">✨</span>
        <h3>No findings!</h3>
        <p>Your code is super clean. Good job!</p>
      </div>
    `;
  } else {
    state.comments.forEach((c, index) => {
      const fileUrl = `file:///${state.repoRoot.replace(/\\/g, '/')}/${c.filePath}`;
      const hasPatch = !!c.suggestedPatch;
      const patchSection = hasPatch ? `
            <div class="detail-section">
              <div class="detail-label">Suggested Solution</div>
              <div class="patch-container">
                <div class="patch-header">
                  <span class="patch-title">${path.basename(c.filePath)} patch</span>
                  <button class="copy-btn" id="copy-btn-${index}" onclick="copyPatch(event, ${index})">📋 Copy Patch</button>
                </div>
                <pre class="patch-code" id="patch-text-${index}">${formatDiffToHtml(c.suggestedPatch || '')}</pre>
              </div>
            </div>` : '';

      findingsHtml += `
        <div class="finding-card severity-${c.severity.toLowerCase()}" 
             data-severity="${c.severity}" 
             data-filepath="${c.filePath}" 
             data-category="${c.category}">
          <div class="finding-header">
            <div class="finding-header-left">
              <div class="finding-meta">
                <span class="badge ${c.severity.toLowerCase()}">${c.severity}</span>
                <span class="category-tag">${c.category}</span>
                <a href="${fileUrl}#L${c.line}" class="finding-file-link" target="_blank">${c.filePath}:${c.line}</a>
              </div>
              <h3 class="finding-title">${escapeHtml(c.title)}</h3>
            </div>
            <div class="chevron-icon">▼</div>
          </div>
          <div class="finding-details">
            <div class="detail-section">
              <div class="detail-label">The Problem</div>
              <p class="detail-content problem-text">${escapeHtml(c.problem)}</p>
            </div>
            <div class="detail-section">
              <div class="detail-label">Why It Matters (Concept)</div>
              <p class="detail-content why-text">${escapeHtml(c.whyItMatters)}</p>
            </div>
            <div class="detail-section">
              <div class="detail-label">Consequences</div>
              <p class="detail-content consequences-text"><em>${escapeHtml(c.consequences)}</em></p>
            </div>
            ${patchSection}
          </div>
        </div>
      `;
    });
  }

  // Build lessons learned
  let takeawaysHtml = '';
  if (totalCount > 0) {
    const uniqueTakeaways = Array.from(new Set(state.comments.map(c => `
          <li class="takeaway-item">
            <span class="takeaway-cat">[${c.category}]</span> <strong>${escapeHtml(c.title)}</strong>: ${escapeHtml(c.whyItMatters)}
          </li>`)));
    takeawaysHtml = `
      <div class="takeaways-card">
        <h3 class="takeaways-title">🎓 Senior Engineer Lessons Learned</h3>
        <ul class="takeaways-list">
          ${uniqueTakeaways.join('')}
        </ul>
      </div>
    `;
  }

  const circumference = 2 * Math.PI * 52;
  const strokeDashoffset = Math.max(0, circumference - (score / 100) * circumference);

  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Code Review Report</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">
  <style>
    :root {
      --bg-page: #0b0f19;
      --bg-sidebar: #0f1626;
      --bg-card: #151f32;
      --bg-hover: #1b2942;
      --border-color: #243557;
      
      --text-title: #f8fafc;
      --text-main: #cbd5e1;
      --text-sub: #94a3b8;
      --text-muted: #64748b;

      --color-high: #f43f5e;
      --color-high-bg: rgba(244, 63, 94, 0.15);
      --color-medium: #fbbf24;
      --color-medium-bg: rgba(251, 191, 36, 0.15);
      --color-low: #38bdf8;
      --color-low-bg: rgba(56, 189, 248, 0.15);
      
      --color-security: #a855f7;
      --color-performance: #ec4899;
      --color-logic: #3b82f6;
      --color-style: #10b981;

      --color-success: #10b981;
      --color-danger: #ef4444;
      
      --font-sans: 'Outfit', sans-serif;
      --font-mono: 'JetBrains Mono', monospace;
    }

    body {
      margin: 0;
      font-family: var(--font-sans);
      background-color: var(--bg-page);
      color: var(--text-main);
      line-height: 1.5;
    }

    .app-layout {
      display: grid;
      grid-template-columns: 320px 1fr;
      min-height: 100vh;
    }

    /* Sidebar Styling */
    .sidebar {
      background-color: var(--bg-sidebar);
      border-right: 1px solid var(--border-color);
      padding: 2rem 1.5rem;
      display: flex;
      flex-direction: column;
      gap: 2rem;
    }

    .logo {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      font-weight: 800;
      font-size: 1.25rem;
      color: var(--text-title);
      background: linear-gradient(to right, #38bdf8, #818cf8);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      padding-bottom: 1rem;
      border-bottom: 1px solid var(--border-color);
    }

    .health-score-container {
      display: flex;
      flex-direction: column;
      align-items: center;
      padding: 1.5rem;
      background-color: var(--bg-card);
      border: 1px solid var(--border-color);
      border-radius: 12px;
      text-align: center;
      box-shadow: 0 4px 12px rgba(0,0,0,0.2);
    }

    .health-title {
      font-size: 0.875rem;
      font-weight: 600;
      color: var(--text-sub);
      margin-bottom: 1rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    /* Circular Gauge */
    .gauge-svg {
      width: 120px;
      height: 120px;
      transform: rotate(-90deg);
    }

    .gauge-track {
      fill: none;
      stroke: #1e293b;
      stroke-width: 8;
    }

    .gauge-progress {
      fill: none;
      stroke-width: 8;
      stroke-linecap: round;
      transition: stroke-dashoffset 0.8s ease-in-out;
    }

    .health-grade {
      font-size: 2.25rem;
      font-weight: 800;
      margin: 0.5rem 0;
      line-height: 1;
    }

    .health-score-label {
      font-size: 0.875rem;
      color: var(--text-muted);
    }

    /* Stats list */
    .sidebar-stats {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 0.5rem;
      width: 100%;
    }

    .stat-item {
      padding: 0.75rem 0.5rem;
      border-radius: 8px;
      background-color: rgba(255,255,255,0.02);
      border: 1px solid var(--border-color);
      text-align: center;
    }

    .stat-item.high { border-color: var(--color-high); }
    .stat-item.medium { border-color: var(--color-medium); }
    .stat-item.low { border-color: var(--color-low); }

    .stat-val {
      font-size: 1.25rem;
      font-weight: 700;
      color: var(--text-title);
    }

    .stat-label {
      font-size: 0.75rem;
      color: var(--text-muted);
      font-weight: 500;
    }

    /* Changed Files List */
    .files-card {
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
    }

    .files-title {
      font-size: 0.875rem;
      font-weight: 600;
      color: var(--text-sub);
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    .files-list {
      display: flex;
      flex-direction: column;
      gap: 0.25rem;
      max-height: 250px;
      overflow-y: auto;
    }

    .file-item {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 0.6rem 0.75rem;
      border-radius: 8px;
      cursor: pointer;
      font-size: 0.875rem;
      transition: all 0.2s ease;
      border: 1px solid transparent;
      color: var(--text-sub);
    }

    .file-item:hover {
      background-color: var(--bg-hover);
      color: var(--text-title);
    }

    .file-item.active {
      background-color: var(--bg-hover);
      border-color: #3b82f6;
      color: var(--text-title);
      font-weight: 600;
    }

    .file-name {
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
      max-width: 200px;
    }

    .file-badge {
      font-size: 0.75rem;
      background-color: var(--border-color);
      color: var(--text-main);
      padding: 0.1rem 0.4rem;
      border-radius: 9999px;
      font-weight: 600;
    }

    /* Main Panel Styling */
    .main-content {
      padding: 2rem 2.5rem;
      display: flex;
      flex-direction: column;
      gap: 2rem;
      overflow-y: auto;
      max-height: 100vh;
    }

    /* Filter controls */
    .controls-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 1rem;
      flex-wrap: wrap;
    }

    .tabs {
      display: flex;
      gap: 0.5rem;
      background-color: var(--bg-sidebar);
      padding: 0.25rem;
      border-radius: 8px;
      border: 1px solid var(--border-color);
    }

    .tab {
      padding: 0.5rem 1rem;
      border-radius: 6px;
      cursor: pointer;
      font-size: 0.875rem;
      font-weight: 500;
      transition: all 0.2s ease;
      border: none;
      background: none;
      color: var(--text-sub);
    }

    .tab:hover {
      color: var(--text-title);
    }

    .tab.active {
      background-color: var(--bg-card);
      color: var(--text-title);
      font-weight: 600;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }

    .search-container {
      display: flex;
      gap: 0.5rem;
      align-items: center;
      flex-grow: 1;
      max-width: 450px;
    }

    .search-input {
      width: 100%;
      padding: 0.5rem 1rem;
      border-radius: 8px;
      background-color: var(--bg-sidebar);
      border: 1px solid var(--border-color);
      color: var(--text-title);
      font-family: inherit;
      font-size: 0.875rem;
      outline: none;
      transition: all 0.2s ease;
    }

    .search-input:focus {
      border-color: #3b82f6;
      box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.2);
    }

    .filter-select {
      padding: 0.5rem 1rem;
      border-radius: 8px;
      background-color: var(--bg-sidebar);
      border: 1px solid var(--border-color);
      color: var(--text-title);
      font-family: inherit;
      font-size: 0.875rem;
      outline: none;
      cursor: pointer;
    }

    /* Goals Card */
    .goals-card {
      background-color: var(--bg-card);
      border: 1px solid var(--border-color);
      border-left: 4px solid #3b82f6;
      border-radius: 12px;
      padding: 1.5rem;
      box-shadow: 0 4px 12px rgba(0,0,0,0.15);
    }

    .goals-title {
      font-weight: 700;
      font-size: 1.1rem;
      color: var(--text-title);
      margin-top: 0;
      margin-bottom: 0.5rem;
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }

    .goals-text {
      font-size: 0.95rem;
      color: var(--text-main);
      margin: 0;
      line-height: 1.6;
    }

    /* Findings list */
    .findings-container {
      display: flex;
      flex-direction: column;
      gap: 1.25rem;
    }

    .finding-card {
      background-color: var(--bg-card);
      border: 1px solid var(--border-color);
      border-radius: 12px;
      overflow: hidden;
      box-shadow: 0 4px 15px rgba(0,0,0,0.15);
      transition: transform 0.2s ease, box-shadow 0.2s ease;
    }

    .finding-card:hover {
      transform: translateY(-2px);
      box-shadow: 0 6px 20px rgba(0,0,0,0.2);
    }

    .finding-card.severity-high { border-left: 4px solid var(--color-high); }
    .finding-card.severity-medium { border-left: 4px solid var(--color-medium); }
    .finding-card.severity-low { border-left: 4px solid var(--color-low); }

    .finding-header {
      padding: 1.25rem 1.5rem;
      display: flex;
      justify-content: space-between;
      align-items: center;
      cursor: pointer;
      user-select: none;
    }

    .finding-header-left {
      display: flex;
      flex-direction: column;
      gap: 0.4rem;
      flex-grow: 1;
    }

    .finding-meta {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      font-size: 0.75rem;
      font-weight: 700;
    }

    .badge {
      padding: 0.15rem 0.5rem;
      border-radius: 4px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    .badge.high { background-color: var(--color-high-bg); color: var(--color-high); }
    .badge.medium { background-color: var(--color-medium-bg); color: var(--color-medium); }
    .badge.low { background-color: var(--color-low-bg); color: var(--color-low); }

    .category-tag {
      color: var(--text-muted);
      background-color: rgba(255,255,255,0.04);
      padding: 0.15rem 0.5rem;
      border-radius: 4px;
      border: 1px solid var(--border-color);
    }

    .finding-file-link {
      color: var(--text-sub);
      text-decoration: none;
    }

    .finding-file-link:hover {
      color: var(--text-title);
      text-decoration: underline;
    }

    .finding-title {
      font-size: 1.15rem;
      font-weight: 700;
      color: var(--text-title);
      margin: 0;
    }

    .chevron-icon {
      font-size: 1.25rem;
      color: var(--text-muted);
      transition: transform 0.3s ease;
    }

    .finding-card.expanded .chevron-icon {
      transform: rotate(180deg);
    }

    .finding-details {
      display: none;
      padding: 0 1.5rem 1.5rem 1.5rem;
      border-top: 1px solid var(--border-color);
      background-color: rgba(0,0,0,0.08);
    }

    .finding-card.expanded .finding-details {
      display: block;
      animation: slideDown 0.25s ease-out;
    }

    .detail-section {
      margin-top: 1.25rem;
    }

    .detail-label {
      font-size: 0.8rem;
      font-weight: 700;
      color: var(--text-sub);
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 0.4rem;
    }

    .detail-content {
      font-size: 0.95rem;
      color: var(--text-main);
      line-height: 1.6;
      margin: 0;
    }

    /* Diff Rendering */
    .patch-container {
      margin-top: 1rem;
      border-radius: 8px;
      border: 1px solid var(--border-color);
      overflow: hidden;
      box-shadow: inset 0 2px 8px rgba(0,0,0,0.3);
    }

    .patch-header {
      background-color: var(--bg-sidebar);
      border-bottom: 1px solid var(--border-color);
      padding: 0.5rem 1rem;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .patch-title {
      font-family: var(--font-mono);
      font-size: 0.8rem;
      color: var(--text-sub);
    }

    .copy-btn {
      background-color: var(--border-color);
      color: var(--text-title);
      border: none;
      padding: 0.35rem 0.75rem;
      border-radius: 4px;
      cursor: pointer;
      font-size: 0.75rem;
      font-weight: 600;
      transition: all 0.2s ease;
      font-family: inherit;
    }

    .copy-btn:hover {
      background-color: var(--bg-hover);
    }

    .patch-code {
      font-family: var(--font-mono);
      font-size: 0.85rem;
      overflow-x: auto;
      background-color: #05070c;
      padding: 0.5rem 0;
      margin: 0;
    }

    .diff-line {
      display: flex;
      padding: 0.15rem 1rem;
    }

    .diff-prefix {
      width: 20px;
      display: inline-block;
      user-select: none;
      font-weight: 700;
    }

    .diff-text {
      white-space: pre;
    }

    .diff-add {
      background-color: rgba(16, 185, 129, 0.12);
      color: #a7f3d0;
    }
    .diff-add .diff-prefix {
      color: #10b981;
    }

    .diff-delete {
      background-color: rgba(239, 68, 68, 0.12);
      color: #fecaca;
    }
    .diff-delete .diff-prefix {
      color: #ef4444;
    }

    .diff-context {
      color: #94a3b8;
    }
    .diff-context .diff-prefix {
      color: #475569;
    }

    /* Empty State */
    .empty-state {
      display: none;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 4rem 2rem;
      background-color: var(--bg-card);
      border: 1px dashed var(--border-color);
      border-radius: 12px;
      color: var(--text-muted);
      text-align: center;
    }

    .empty-state-icon {
      font-size: 3rem;
      margin-bottom: 1rem;
    }

    /* Takeaways section */
    .takeaways-card {
      background-color: var(--bg-card);
      border: 1px solid var(--border-color);
      border-radius: 12px;
      padding: 1.5rem 2rem;
      box-shadow: 0 4px 15px rgba(0,0,0,0.15);
    }

    .takeaways-title {
      font-size: 1.2rem;
      font-weight: 700;
      color: var(--text-title);
      margin-top: 0;
      margin-bottom: 1rem;
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }

    .takeaways-list {
      padding-left: 1.25rem;
      margin: 0;
      display: flex;
      flex-direction: column;
      gap: 0.75rem;
    }

    .takeaway-item {
      font-size: 0.95rem;
      color: var(--text-main);
      line-height: 1.6;
    }

    .takeaway-cat {
      font-weight: 700;
      color: var(--text-title);
    }

    /* Scrollbars */
    ::-webkit-scrollbar {
      width: 8px;
      height: 8px;
    }
    ::-webkit-scrollbar-track {
      background: var(--bg-page);
    }
    ::-webkit-scrollbar-thumb {
      background: var(--border-color);
      border-radius: 4px;
    }
    ::-webkit-scrollbar-thumb:hover {
      background: var(--bg-hover);
    }

    /* Animations */
    @keyframes slideDown {
      from { opacity: 0; transform: translateY(-10px); }
      to { opacity: 1; transform: translateY(0); }
    }
  </style>
</head>
<body>
  <div class="app-layout">
    <!-- Sidebar -->
    <div class="sidebar">
      <div class="logo">
        <span>🤖 GEMINI REVIEWER</span>
      </div>
      
      <!-- Code Health Score -->
      <div class="health-score-container">
        <span class="health-title">Code Health</span>
        <div style="position: relative; width: 120px; height: 120px; display: flex; align-items: center; justify-content: center;">
          <svg class="gauge-svg">
            <circle class="gauge-track" cx="60" cy="60" r="52"></circle>
            <circle class="gauge-progress" cx="60" cy="60" r="52" 
                    style="stroke: ${gradeColor}; stroke-dasharray: ${circumference}; stroke-dashoffset: ${strokeDashoffset};"></circle>
          </svg>
          <div style="position: absolute; display: flex; flex-direction: column; align-items: center; justify-content: center;">
            <span class="health-grade" style="color: ${gradeColor};">${grade}</span>
            <span class="health-score-label">${score}/100</span>
          </div>
        </div>
      </div>

      <!-- Quick Metrics -->
      <div class="sidebar-stats">
        <div class="stat-item high">
          <div class="stat-val" style="color: var(--color-high);">${highCount}</div>
          <div class="stat-label">High</div>
        </div>
        <div class="stat-item medium">
          <div class="stat-val" style="color: var(--color-medium);">${medCount}</div>
          <div class="stat-label">Medium</div>
        </div>
        <div class="stat-item low">
          <div class="stat-val" style="color: var(--color-low);">${lowCount}</div>
          <div class="stat-label">Low</div>
        </div>
      </div>

      <!-- Changed Files -->
      <div class="files-card">
        <span class="files-title">Changed Files</span>
        <div class="files-list">
          <div class="file-item active" data-filepath="ALL">
            <span class="file-name">All Files</span>
            <span class="file-badge" style="background-color: #3b82f6;">${totalCount}</span>
          </div>
          ${fileListHtml}
        </div>
      </div>
    </div>

    <!-- Main Content -->
    <div class="main-content">
      <!-- Search & Filters -->
      <div class="controls-row">
        <div class="tabs">
          <button class="tab active" data-severity="ALL">All Severities</button>
          <button class="tab" data-severity="HIGH" style="color: var(--color-high);">🔴 High</button>
          <button class="tab" data-severity="MEDIUM" style="color: var(--color-medium);">🟡 Medium</button>
          <button class="tab" data-severity="LOW" style="color: var(--color-low);">🔵 Low</button>
        </div>

        <div class="search-container">
          <input type="text" id="search-input" class="search-input" placeholder="🔍 Search findings...">
          <select id="category-filter" class="filter-select">
            <option value="ALL">All Categories</option>
            <option value="Security">🛡️ Security</option>
            <option value="Performance">⚡ Performance</option>
            <option value="Logic">🧠 Logic</option>
            <option value="Style">🎨 Style</option>
          </select>
        </div>
      </div>

      <!-- Review Focus Goals -->
      ${state.plannerGoals ? `
      <div class="goals-card">
        <h4 class="goals-title">🎯 Review Focus & Goals</h4>
        <p class="goals-text">${escapeHtml(state.plannerGoals)}</p>
      </div>
      ` : ''}

      <!-- Findings List -->
      <div class="findings-container">
        ${findingsHtml}
        
        <!-- Filter Empty State -->
        <div class="empty-state" id="filter-empty-state">
          <span class="empty-state-icon">🔍</span>
          <h3>No matching findings</h3>
          <p>Try adjusting your search query or filter options.</p>
        </div>
      </div>

      <!-- Takeaways (Lessons Learned) -->
      ${takeawaysHtml}
    </div>
  </div>

  <script>
    let activeSeverity = 'ALL';
    let activeFile = 'ALL';
    let activeCategory = 'ALL';
    let searchQuery = '';

    const cards = document.querySelectorAll('.finding-card');
    const fileItems = document.querySelectorAll('.file-item');
    const severityTabs = document.querySelectorAll('.tab');
    const categoryFilter = document.getElementById('category-filter');
    const searchInput = document.getElementById('search-input');
    const emptyState = document.getElementById('filter-empty-state');

    function updateFilters() {
      let visibleCount = 0;
      cards.forEach(card => {
        const severityMatch = activeSeverity === 'ALL' || card.dataset.severity === activeSeverity;
        const fileMatch = activeFile === 'ALL' || card.dataset.filepath === activeFile;
        const categoryMatch = activeCategory === 'ALL' || card.dataset.category === activeCategory;
        
        const searchText = (card.querySelector('.finding-title').textContent + ' ' + 
                            card.querySelector('.problem-text').textContent + ' ' + 
                            card.querySelector('.why-text').textContent).toLowerCase();
        const searchMatch = searchQuery === '' || searchText.includes(searchQuery);

        if (severityMatch && fileMatch && categoryMatch && searchMatch) {
          card.style.display = 'block';
          visibleCount++;
        } else {
          card.style.display = 'none';
        }
      });

      if (visibleCount === 0 && cards.length > 0) {
        emptyState.style.display = 'flex';
      } else {
        emptyState.style.display = 'none';
      }
    }

    // Event Listeners
    severityTabs.forEach(tab => {
      tab.addEventListener('click', () => {
        severityTabs.forEach(t => t.classList.remove('active'));
        tab.classList.add('active');
        activeSeverity = tab.dataset.severity;
        updateFilters();
      });
    });

    fileItems.forEach(item => {
      item.addEventListener('click', () => {
        fileItems.forEach(i => i.classList.remove('active'));
        item.classList.add('active');
        activeFile = item.dataset.filepath;
        updateFilters();
      });
    });

    if (categoryFilter) {
      categoryFilter.addEventListener('change', (e) => {
        activeCategory = e.target.value;
        updateFilters();
      });
    }

    if (searchInput) {
      searchInput.addEventListener('input', (e) => {
        searchQuery = e.target.value.toLowerCase().trim();
        updateFilters();
      });
    }

    // Toggle detail card collapse
    document.querySelectorAll('.finding-header').forEach(header => {
      header.addEventListener('click', () => {
        const card = header.parentElement;
        card.classList.toggle('expanded');
      });
    });

    // Copy patch function
    function copyPatch(event, id) {
      event.stopPropagation(); // stop click from triggering card collapse toggle
      const codeBlock = document.getElementById('patch-text-' + id);
      if (!codeBlock) return;
      
      const lines = Array.from(codeBlock.querySelectorAll('.diff-line')).map(line => {
        const prefix = line.querySelector('.diff-prefix').textContent;
        const text = line.querySelector('.diff-text').textContent;
        return prefix + text;
      }).join('\\\\n');

      navigator.clipboard.writeText(lines).then(() => {
        const btn = document.getElementById('copy-btn-' + id);
        const originalText = btn.innerHTML;
        btn.innerHTML = '📋 Copied!';
        btn.style.backgroundColor = '#10b981';
        setTimeout(() => {
          btn.innerHTML = originalText;
          btn.style.backgroundColor = '';
        }, 2000);
      });
    }
  </script>
</body>
</html>`;

  fs.writeFileSync(reportPath, htmlContent, 'utf-8');
}

