import * as fs from 'fs';
import * as path from 'path';
import { ReviewState, ReviewComment } from './orchestrator.js';

// Color logging helpers for terminal
const RESET = '\x1b[0m';
const BOLD = '\x1b[1m';
const RED = '\x1b[31m';
const YELLOW = '\x1b[33m';
const CYAN = '\x1b[36m';
const GREEN = '\x1b[32m';

/**
 * Outputs the review findings to the console with beautiful coloring.
 */
export function reportToConsole(state: ReviewState): void {
  const { comments } = state;
  console.log(`\n${BOLD}==================================================`);
  console.log(`🚀 ${GREEN}GEMINI CODE REVIEW COMPLETE${RESET}`);
  console.log(`${BOLD}==================================================${RESET}`);

  if (comments.length === 0) {
    console.log(`\n✨ ${GREEN}No issues found! Your code looks clean and solid.${RESET}\n`);
    return;
  }

  const highCount = comments.filter(c => c.severity === 'HIGH').length;
  const medCount = comments.filter(c => c.severity === 'MEDIUM').length;
  const lowCount = comments.filter(c => c.severity === 'LOW').length;

  console.log(`\nFound ${BOLD}${comments.length} issues${RESET}:`);
  console.log(`- 🔴 ${RED}${highCount} High severity${RESET}`);
  console.log(`- 🟡 ${YELLOW}${medCount} Medium severity${RESET}`);
  console.log(`- 🔵 ${CYAN}${lowCount} Low severity${RESET}\n`);

  comments.forEach((c, index) => {
    let severityColor = CYAN;
    let severityIcon = '🔵';
    if (c.severity === 'HIGH') {
      severityColor = RED;
      severityIcon = '🔴';
    } else if (c.severity === 'MEDIUM') {
      severityColor = YELLOW;
      severityIcon = '🟡';
    }

    console.log(`${BOLD}${index + 1}. ${severityIcon} ${severityColor}[${c.severity}]${RESET} ${BOLD}${c.category}:${RESET} ${c.title}`);
    console.log(`   ${BOLD}File:${RESET} ${c.filePath}:${c.line}`);
    console.log(`   ${BOLD}Problem:${RESET} ${c.problem}`);
    console.log(`   ${BOLD}Consequences:${RESET} ${c.consequences}`);
    if (c.suggestedPatch) {
      console.log(`   ${BOLD}Suggested Fix Available in REVIEW_REPORT.md${RESET}`);
    }
    console.log('-'.repeat(50));
  });

  console.log(`\n📝 ${BOLD}Detailed report written to: REVIEW_REPORT.md${RESET}\n`);
}

/**
 * Writes an educational Markdown report to `REVIEW_REPORT.md` in the git root.
 */
export function writeMarkdownReport(state: ReviewState): void {
  const reportPath = path.join(state.repoRoot, 'REVIEW_REPORT.md');

  const highCount = state.comments.filter(c => c.severity === 'HIGH').length;
  const medCount = state.comments.filter(c => c.severity === 'MEDIUM').length;
  const lowCount = state.comments.filter(c => c.severity === 'LOW').length;

  let mdContent = `# 🚀 AI Code Review Report\n\n`;
  mdContent += `This report was automatically generated by the Gemini Code Reviewer. It contains deep, educational analysis of your staged/unstaged changes.\n\n`;

  // Summary Card
  mdContent += `## 📊 Review Summary\n\n`;
  if (state.comments.length === 0) {
    mdContent += `> ✨ **No issues found!** Your code looks clean, robust, and well-structured.\n\n`;
  } else {
    mdContent += `* **Total Issues**: ${state.comments.length}\n`;
    mdContent += `* 🔴 **High Severity**: ${highCount}\n`;
    mdContent += `* 🟡 **Medium Severity**: ${medCount}\n`;
    mdContent += `* 🔵 **Low Severity**: ${lowCount}\n\n`;
    if (state.plannerGoals) {
      mdContent += `> **Overall Goals/Focus of this Review**: ${state.plannerGoals}\n\n`;
    }
  }

  // Group by File Path
  const commentsByFile: Record<string, ReviewComment[]> = {};
  state.comments.forEach(c => {
    if (!commentsByFile[c.filePath]) {
      commentsByFile[c.filePath] = [];
    }
    commentsByFile[c.filePath].push(c);
  });

  if (state.comments.length > 0) {
    mdContent += `## 🔍 Findings by File\n\n`;

    Object.entries(commentsByFile).forEach(([filePath, fileComments]) => {
      const fileUrl = `file:///${state.repoRoot.replace(/\\/g, '/')}/${filePath}`;
      mdContent += `### 📁 File: [${path.basename(filePath)}](${fileUrl})\n`;
      mdContent += `Path: \`${filePath}\`\n\n`;

      fileComments.forEach(c => {
        let severityIcon = '🔵';
        if (c.severity === 'HIGH') severityIcon = '🔴';
        if (c.severity === 'MEDIUM') severityIcon = '🟡';

        mdContent += `#### ${severityIcon} **${c.severity}** | **${c.category}**: ${c.title}\n`;
        mdContent += `* **Line**: [${c.line}](${fileUrl}#L${c.line})\n`;
        mdContent += `* **The Problem**: ${c.problem}\n`;
        mdContent += `* **Why It Matters (Concept)**: ${c.whyItMatters}\n`;
        mdContent += `* **Consequences**: *${c.consequences}*\n\n`;

        if (c.suggestedPatch) {
          // Format as a markdown diff block or code block
          mdContent += `**Suggested Solution:**\n`;
          mdContent += `\`\`\`diff\n`;
          
          // Split the patch into lines and prefix if not already formatted as a diff
          const patchLines = c.suggestedPatch.split('\n');
          const formattedPatch = patchLines.map(l => {
            if (l.startsWith('+') || l.startsWith('-')) return l;
            return `+ ${l}`; // default to green line if model forgot prefix
          }).join('\n');

          mdContent += `${formattedPatch}\n`;
          mdContent += `\`\`\`\n\n`;
        }

        mdContent += `---\n\n`;
      });
    });

    // Add educational takeaways section
    mdContent += `## 🎓 Senior Engineer Lessons learned\n\n`;
    mdContent += `Here is a summary of the concepts and design principles raised in this review. Use these to strengthen your codebase and development practices:\n\n`;

    const uniqueTakeaways = Array.from(new Set(state.comments.map(c => `* **${c.category} (${c.title})**: ${c.whyItMatters}`)));
    mdContent += uniqueTakeaways.join('\n\n') + '\n';
  }

  fs.writeFileSync(reportPath, mdContent, 'utf-8');
}
